const PDFDocument = require('pdfkit');

// Generate a pre-acceptance letter PDF. Returns a Buffer.
function generatePreAcceptancePdf(app, ref, conditional) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 60 });
    const bufs = [];
    doc.on('data', d => bufs.push(d));
    doc.on('end', () => resolve(Buffer.concat(bufs)));
    doc.on('error', reject);

    const name = [app.first_name, app.last_name].filter(Boolean).join(' ') || 'Applicant';
    const uni  = app.university_name || 'the university';
    const prog = app.program_name   || '';
    const heading = conditional ? 'CONDITIONAL ACCEPTANCE LETTER' : 'PRE-ACCEPTANCE LETTER';
    const today = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

    // ── Header bar ──────────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 90).fill('#6366f1');
    doc.fillColor('#ffffff')
       .fontSize(22).font('Helvetica-Bold')
       .text('PANELEDU', 60, 28);
    doc.fontSize(9).font('Helvetica')
       .text('Study Abroad Advisory Platform', 60, 54);
    doc.fillColor('#000000');

    // ── Reference & date ────────────────────────────────────────────────
    doc.moveDown(4);
    doc.fontSize(9).font('Helvetica').fillColor('#64748b')
       .text(`Reference: ${ref}`, { align: 'right' })
       .text(`Date: ${today}`, { align: 'right' });

    // ── Heading ─────────────────────────────────────────────────────────
    doc.moveDown(1.5);
    doc.fontSize(16).font('Helvetica-Bold').fillColor('#6366f1')
       .text(heading, { align: 'center' });
    doc.moveDown(0.3);
    doc.moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y)
       .strokeColor('#e2e8f0').lineWidth(1).stroke();

    // ── Body ─────────────────────────────────────────────────────────────
    doc.moveDown(1.2);
    doc.fontSize(11).font('Helvetica').fillColor('#1e293b');

    doc.text(`Dear ${name},`);
    doc.moveDown(0.8);

    const intro = conditional
      ? `We are pleased to inform you that, following the preliminary assessment of your academic profile, you have received a Conditional Pre-Acceptance for:`
      : `We are pleased to inform you that, following the preliminary assessment of your academic profile, you have received a Pre-Acceptance for:`;
    doc.text(intro, { lineGap: 4 });

    // ── Program box ─────────────────────────────────────────────────────
    doc.moveDown(0.8);
    const boxY = doc.y;
    doc.rect(60, boxY, doc.page.width - 120, prog ? 68 : 50)
       .fillColor('#f8fafc').fill();
    doc.rect(60, boxY, doc.page.width - 120, prog ? 68 : 50)
       .strokeColor('#e2e8f0').lineWidth(1).stroke();

    doc.fillColor('#64748b').fontSize(9).font('Helvetica')
       .text('University', 76, boxY + 10);
    doc.fillColor('#1e293b').fontSize(11).font('Helvetica-Bold')
       .text(uni, 76, boxY + 22);
    if (prog) {
      doc.fillColor('#64748b').fontSize(9).font('Helvetica')
         .text('Programme', 76, boxY + 44);
      doc.fillColor('#1e293b').fontSize(10).font('Helvetica')
         .text(prog, 76, boxY + 56);
    }
    doc.moveDown(prog ? 4.5 : 3.5);

    // ── Conditions ───────────────────────────────────────────────────────
    if (conditional && app.preaccept_conditions) {
      doc.moveDown(0.4);
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#b45309')
         .text('Conditions:');
      doc.fontSize(10).font('Helvetica').fillColor('#1e293b')
         .text(app.preaccept_conditions, { lineGap: 4 });
      doc.moveDown(0.6);
    }

    // ── Closing ──────────────────────────────────────────────────────────
    doc.moveDown(0.8);
    doc.fontSize(11).font('Helvetica').fillColor('#1e293b')
       .text(
         'This letter represents a PANELEDU preliminary assessment and is not a final admission decision by the university. ' +
         'Our advisors will guide you through the next steps of the formal application process.',
         { lineGap: 4 }
       );
    doc.moveDown(1.2);
    doc.text('We look forward to supporting your study abroad journey.');
    doc.moveDown(1.5);
    doc.font('Helvetica-Bold').text('PANELEDU Admissions Team');
    doc.font('Helvetica').fillColor('#6366f1').text('paneledu.com');

    // ── Footer ───────────────────────────────────────────────────────────
    const footerY = doc.page.height - 50;
    doc.moveTo(60, footerY).lineTo(doc.page.width - 60, footerY)
       .strokeColor('#e2e8f0').lineWidth(1).stroke();
    doc.fontSize(8).fillColor('#94a3b8').font('Helvetica')
       .text(
         `This document was generated by PANELEDU. Reference: ${ref}`,
         60, footerY + 10,
         { align: 'center', width: doc.page.width - 120 }
       );

    doc.end();
  });
}

module.exports = { generatePreAcceptancePdf };
